// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductStockApi.Data;

#nullable disable

namespace ProductStockApi.Data.Migrations
{
    [DbContext(typeof(ProductStockContext))]
    partial class ProductStockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductStockApi.Data.ProductStock", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Productid"), 1L, 1);

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Productid");

                    b.ToTable("ProductStocks");

                    b.HasData(
                        new
                        {
                            Productid = 1,
                            Stock = 100
                        },
                        new
                        {
                            Productid = 2,
                            Stock = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
